#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("BethanysPieShop.Mobile.Droid.Resource", IsApplication=true)]

namespace BethanysPieShop.Mobile.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::AndroidHUD.Resource.Attribute.ahBarColor = global::BethanysPieShop.Mobile.Droid.Resource.Attribute.ahBarColor;
			global::AndroidHUD.Resource.Attribute.ahBarLength = global::BethanysPieShop.Mobile.Droid.Resource.Attribute.ahBarLength;
			global::AndroidHUD.Resource.Attribute.ahBarWidth = global::BethanysPieShop.Mobile.Droid.Resource.Attribute.ahBarWidth;
			global::AndroidHUD.Resource.Attribute.ahCircleColor = global::BethanysPieShop.Mobile.Droid.Resource.Attribute.ahCircleColor;
			global::AndroidHUD.Resource.Attribute.ahDelayMillis = global::BethanysPieShop.Mobile.Droid.Resource.Attribute.ahDelayMillis;
			global::AndroidHUD.Resource.Attribute.ahRadius = global::BethanysPieShop.Mobile.Droid.Resource.Attribute.ahRadius;
			global::AndroidHUD.Resource.Attribute.ahRimColor = global::BethanysPieShop.Mobile.Droid.Resource.Attribute.ahRimColor;
			global::AndroidHUD.Resource.Attribute.ahRimWidth = global::BethanysPieShop.Mobile.Droid.Resource.Attribute.ahRimWidth;
			global::AndroidHUD.Resource.Attribute.ahSpinSpeed = global::BethanysPieShop.Mobile.Droid.Resource.Attribute.ahSpinSpeed;
			global::AndroidHUD.Resource.Attribute.ahText = global::BethanysPieShop.Mobile.Droid.Resource.Attribute.ahText;
			global::AndroidHUD.Resource.Attribute.ahTextColor = global::BethanysPieShop.Mobile.Droid.Resource.Attribute.ahTextColor;
			global::AndroidHUD.Resource.Attribute.ahTextSize = global::BethanysPieShop.Mobile.Droid.Resource.Attribute.ahTextSize;
			global::AndroidHUD.Resource.Drawable.ic_errorstatus = global::BethanysPieShop.Mobile.Droid.Resource.Drawable.ic_errorstatus;
			global::AndroidHUD.Resource.Drawable.ic_successstatus = global::BethanysPieShop.Mobile.Droid.Resource.Drawable.ic_successstatus;
			global::AndroidHUD.Resource.Drawable.roundedbg = global::BethanysPieShop.Mobile.Droid.Resource.Drawable.roundedbg;
			global::AndroidHUD.Resource.Drawable.roundedbgdark = global::BethanysPieShop.Mobile.Droid.Resource.Drawable.roundedbgdark;
			global::AndroidHUD.Resource.Id.loadingImage = global::BethanysPieShop.Mobile.Droid.Resource.Id.loadingImage;
			global::AndroidHUD.Resource.Id.loadingProgressBar = global::BethanysPieShop.Mobile.Droid.Resource.Id.loadingProgressBar;
			global::AndroidHUD.Resource.Id.loadingProgressWheel = global::BethanysPieShop.Mobile.Droid.Resource.Id.loadingProgressWheel;
			global::AndroidHUD.Resource.Id.textViewStatus = global::BethanysPieShop.Mobile.Droid.Resource.Id.textViewStatus;
			global::AndroidHUD.Resource.Layout.loading = global::BethanysPieShop.Mobile.Droid.Resource.Layout.loading;
			global::AndroidHUD.Resource.Layout.loadingimage = global::BethanysPieShop.Mobile.Droid.Resource.Layout.loadingimage;
			global::AndroidHUD.Resource.Layout.loadingprogress = global::BethanysPieShop.Mobile.Droid.Resource.Layout.loadingprogress;
			global::AndroidHUD.Resource.String.library_name = global::BethanysPieShop.Mobile.Droid.Resource.String.library_name;
			global::AndroidHUD.Resource.Styleable.ProgressWheel = global::BethanysPieShop.Mobile.Droid.Resource.Styleable.ProgressWheel;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahBarColor = global::BethanysPieShop.Mobile.Droid.Resource.Styleable.ProgressWheel_ahBarColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahBarLength = global::BethanysPieShop.Mobile.Droid.Resource.Styleable.ProgressWheel_ahBarLength;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahBarWidth = global::BethanysPieShop.Mobile.Droid.Resource.Styleable.ProgressWheel_ahBarWidth;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahCircleColor = global::BethanysPieShop.Mobile.Droid.Resource.Styleable.ProgressWheel_ahCircleColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahDelayMillis = global::BethanysPieShop.Mobile.Droid.Resource.Styleable.ProgressWheel_ahDelayMillis;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahRadius = global::BethanysPieShop.Mobile.Droid.Resource.Styleable.ProgressWheel_ahRadius;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahRimColor = global::BethanysPieShop.Mobile.Droid.Resource.Styleable.ProgressWheel_ahRimColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahRimWidth = global::BethanysPieShop.Mobile.Droid.Resource.Styleable.ProgressWheel_ahRimWidth;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahSpinSpeed = global::BethanysPieShop.Mobile.Droid.Resource.Styleable.ProgressWheel_ahSpinSpeed;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahText = global::BethanysPieShop.Mobile.Droid.Resource.Styleable.ProgressWheel_ahText;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahTextColor = global::BethanysPieShop.Mobile.Droid.Resource.Styleable.ProgressWheel_ahTextColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahTextSize = global::BethanysPieShop.Mobile.Droid.Resource.Styleable.ProgressWheel_ahTextSize;
			global::Splat.Resource.String.library_name = global::BethanysPieShop.Mobile.Droid.Resource.String.library_name;
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7F010000
			public const int design_bottom_sheet_slide_in = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int design_bottom_sheet_slide_out = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int design_snackbar_in = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int design_snackbar_out = 2130771971;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Animator
		{
			
			// aapt resource value: 0x7F020000
			public const int design_appbar_state_list_animator = 2130837504;
			
			static Animator()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animator()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7F030000
			public const int ahBarColor = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int ahBarLength = 2130903041;
			
			// aapt resource value: 0x7F030002
			public const int ahBarWidth = 2130903042;
			
			// aapt resource value: 0x7F030003
			public const int ahCircleColor = 2130903043;
			
			// aapt resource value: 0x7F030004
			public const int ahDelayMillis = 2130903044;
			
			// aapt resource value: 0x7F030005
			public const int ahRadius = 2130903045;
			
			// aapt resource value: 0x7F030006
			public const int ahRimColor = 2130903046;
			
			// aapt resource value: 0x7F030007
			public const int ahRimWidth = 2130903047;
			
			// aapt resource value: 0x7F030008
			public const int ahSpinSpeed = 2130903048;
			
			// aapt resource value: 0x7F030009
			public const int ahText = 2130903049;
			
			// aapt resource value: 0x7F03000A
			public const int ahTextColor = 2130903050;
			
			// aapt resource value: 0x7F03000B
			public const int ahTextSize = 2130903051;
			
			// aapt resource value: 0x7F03000C
			public const int backgroundTint = 2130903052;
			
			// aapt resource value: 0x7F03000D
			public const int backgroundTintMode = 2130903053;
			
			// aapt resource value: 0x7F03000E
			public const int behavior_autoHide = 2130903054;
			
			// aapt resource value: 0x7F03000F
			public const int behavior_hideable = 2130903055;
			
			// aapt resource value: 0x7F030010
			public const int behavior_overlapTop = 2130903056;
			
			// aapt resource value: 0x7F030011
			public const int behavior_peekHeight = 2130903057;
			
			// aapt resource value: 0x7F030012
			public const int behavior_skipCollapsed = 2130903058;
			
			// aapt resource value: 0x7F030013
			public const int borderWidth = 2130903059;
			
			// aapt resource value: 0x7F030014
			public const int bottomSheetDialogTheme = 2130903060;
			
			// aapt resource value: 0x7F030015
			public const int bottomSheetStyle = 2130903061;
			
			// aapt resource value: 0x7F030016
			public const int collapsedTitleGravity = 2130903062;
			
			// aapt resource value: 0x7F030017
			public const int collapsedTitleTextAppearance = 2130903063;
			
			// aapt resource value: 0x7F030018
			public const int contentScrim = 2130903064;
			
			// aapt resource value: 0x7F030019
			public const int counterEnabled = 2130903065;
			
			// aapt resource value: 0x7F03001A
			public const int counterMaxLength = 2130903066;
			
			// aapt resource value: 0x7F03001B
			public const int counterOverflowTextAppearance = 2130903067;
			
			// aapt resource value: 0x7F03001C
			public const int counterTextAppearance = 2130903068;
			
			// aapt resource value: 0x7F03001D
			public const int elevation = 2130903069;
			
			// aapt resource value: 0x7F03001E
			public const int errorEnabled = 2130903070;
			
			// aapt resource value: 0x7F03001F
			public const int errorTextAppearance = 2130903071;
			
			// aapt resource value: 0x7F030020
			public const int expanded = 2130903072;
			
			// aapt resource value: 0x7F030021
			public const int expandedTitleGravity = 2130903073;
			
			// aapt resource value: 0x7F030022
			public const int expandedTitleMargin = 2130903074;
			
			// aapt resource value: 0x7F030023
			public const int expandedTitleMarginBottom = 2130903075;
			
			// aapt resource value: 0x7F030024
			public const int expandedTitleMarginEnd = 2130903076;
			
			// aapt resource value: 0x7F030025
			public const int expandedTitleMarginStart = 2130903077;
			
			// aapt resource value: 0x7F030026
			public const int expandedTitleMarginTop = 2130903078;
			
			// aapt resource value: 0x7F030027
			public const int expandedTitleTextAppearance = 2130903079;
			
			// aapt resource value: 0x7F030028
			public const int fabSize = 2130903080;
			
			// aapt resource value: 0x7F030029
			public const int font = 2130903081;
			
			// aapt resource value: 0x7F03002A
			public const int fontProviderAuthority = 2130903082;
			
			// aapt resource value: 0x7F03002B
			public const int fontProviderCerts = 2130903083;
			
			// aapt resource value: 0x7F03002C
			public const int fontProviderFetchStrategy = 2130903084;
			
			// aapt resource value: 0x7F03002D
			public const int fontProviderFetchTimeout = 2130903085;
			
			// aapt resource value: 0x7F03002E
			public const int fontProviderPackage = 2130903086;
			
			// aapt resource value: 0x7F03002F
			public const int fontProviderQuery = 2130903087;
			
			// aapt resource value: 0x7F030030
			public const int fontStyle = 2130903088;
			
			// aapt resource value: 0x7F030031
			public const int fontWeight = 2130903089;
			
			// aapt resource value: 0x7F030032
			public const int foregroundInsidePadding = 2130903090;
			
			// aapt resource value: 0x7F030033
			public const int headerLayout = 2130903091;
			
			// aapt resource value: 0x7F030034
			public const int hintAnimationEnabled = 2130903092;
			
			// aapt resource value: 0x7F030035
			public const int hintEnabled = 2130903093;
			
			// aapt resource value: 0x7F030036
			public const int hintTextAppearance = 2130903094;
			
			// aapt resource value: 0x7F030037
			public const int insetForeground = 2130903095;
			
			// aapt resource value: 0x7F030038
			public const int itemBackground = 2130903096;
			
			// aapt resource value: 0x7F030039
			public const int itemIconTint = 2130903097;
			
			// aapt resource value: 0x7F03003A
			public const int itemTextAppearance = 2130903098;
			
			// aapt resource value: 0x7F03003B
			public const int itemTextColor = 2130903099;
			
			// aapt resource value: 0x7F03003C
			public const int keylines = 2130903100;
			
			// aapt resource value: 0x7F03003D
			public const int layout_anchor = 2130903101;
			
			// aapt resource value: 0x7F03003E
			public const int layout_anchorGravity = 2130903102;
			
			// aapt resource value: 0x7F03003F
			public const int layout_behavior = 2130903103;
			
			// aapt resource value: 0x7F030040
			public const int layout_collapseMode = 2130903104;
			
			// aapt resource value: 0x7F030041
			public const int layout_collapseParallaxMultiplier = 2130903105;
			
			// aapt resource value: 0x7F030042
			public const int layout_dodgeInsetEdges = 2130903106;
			
			// aapt resource value: 0x7F030043
			public const int layout_insetEdge = 2130903107;
			
			// aapt resource value: 0x7F030044
			public const int layout_keyline = 2130903108;
			
			// aapt resource value: 0x7F030045
			public const int layout_scrollFlags = 2130903109;
			
			// aapt resource value: 0x7F030046
			public const int layout_scrollInterpolator = 2130903110;
			
			// aapt resource value: 0x7F030047
			public const int maxActionInlineWidth = 2130903111;
			
			// aapt resource value: 0x7F030048
			public const int menu = 2130903112;
			
			// aapt resource value: 0x7F030049
			public const int passwordToggleContentDescription = 2130903113;
			
			// aapt resource value: 0x7F03004A
			public const int passwordToggleDrawable = 2130903114;
			
			// aapt resource value: 0x7F03004B
			public const int passwordToggleEnabled = 2130903115;
			
			// aapt resource value: 0x7F03004C
			public const int passwordToggleTint = 2130903116;
			
			// aapt resource value: 0x7F03004D
			public const int passwordToggleTintMode = 2130903117;
			
			// aapt resource value: 0x7F03004E
			public const int pressedTranslationZ = 2130903118;
			
			// aapt resource value: 0x7F03004F
			public const int rippleColor = 2130903119;
			
			// aapt resource value: 0x7F030050
			public const int scrimAnimationDuration = 2130903120;
			
			// aapt resource value: 0x7F030051
			public const int scrimVisibleHeightTrigger = 2130903121;
			
			// aapt resource value: 0x7F030052
			public const int state_collapsed = 2130903122;
			
			// aapt resource value: 0x7F030053
			public const int state_collapsible = 2130903123;
			
			// aapt resource value: 0x7F030054
			public const int statusBarBackground = 2130903124;
			
			// aapt resource value: 0x7F030055
			public const int statusBarScrim = 2130903125;
			
			// aapt resource value: 0x7F030056
			public const int tabBackground = 2130903126;
			
			// aapt resource value: 0x7F030057
			public const int tabContentStart = 2130903127;
			
			// aapt resource value: 0x7F030058
			public const int tabGravity = 2130903128;
			
			// aapt resource value: 0x7F030059
			public const int tabIndicatorColor = 2130903129;
			
			// aapt resource value: 0x7F03005A
			public const int tabIndicatorHeight = 2130903130;
			
			// aapt resource value: 0x7F03005B
			public const int tabMaxWidth = 2130903131;
			
			// aapt resource value: 0x7F03005C
			public const int tabMinWidth = 2130903132;
			
			// aapt resource value: 0x7F03005D
			public const int tabMode = 2130903133;
			
			// aapt resource value: 0x7F03005E
			public const int tabPadding = 2130903134;
			
			// aapt resource value: 0x7F03005F
			public const int tabPaddingBottom = 2130903135;
			
			// aapt resource value: 0x7F030060
			public const int tabPaddingEnd = 2130903136;
			
			// aapt resource value: 0x7F030061
			public const int tabPaddingStart = 2130903137;
			
			// aapt resource value: 0x7F030062
			public const int tabPaddingTop = 2130903138;
			
			// aapt resource value: 0x7F030063
			public const int tabSelectedTextColor = 2130903139;
			
			// aapt resource value: 0x7F030064
			public const int tabTextAppearance = 2130903140;
			
			// aapt resource value: 0x7F030065
			public const int tabTextColor = 2130903141;
			
			// aapt resource value: 0x7F030066
			public const int textColorError = 2130903142;
			
			// aapt resource value: 0x7F030067
			public const int title = 2130903143;
			
			// aapt resource value: 0x7F030068
			public const int titleEnabled = 2130903144;
			
			// aapt resource value: 0x7F030069
			public const int toolbarId = 2130903145;
			
			// aapt resource value: 0x7F03006A
			public const int useCompatPadding = 2130903146;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Boolean
		{
			
			// aapt resource value: 0x7F040000
			public const int abc_action_bar_embed_tabs = 2130968576;
			
			static Boolean()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Boolean()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F050000
			public const int design_bottom_navigation_shadow_color = 2131034112;
			
			// aapt resource value: 0x7F050001
			public const int design_error = 2131034113;
			
			// aapt resource value: 0x7F050002
			public const int design_fab_shadow_end_color = 2131034114;
			
			// aapt resource value: 0x7F050003
			public const int design_fab_shadow_mid_color = 2131034115;
			
			// aapt resource value: 0x7F050004
			public const int design_fab_shadow_start_color = 2131034116;
			
			// aapt resource value: 0x7F050005
			public const int design_fab_stroke_end_inner_color = 2131034117;
			
			// aapt resource value: 0x7F050006
			public const int design_fab_stroke_end_outer_color = 2131034118;
			
			// aapt resource value: 0x7F050007
			public const int design_fab_stroke_top_inner_color = 2131034119;
			
			// aapt resource value: 0x7F050008
			public const int design_fab_stroke_top_outer_color = 2131034120;
			
			// aapt resource value: 0x7F050009
			public const int design_snackbar_background_color = 2131034121;
			
			// aapt resource value: 0x7F05000A
			public const int design_tint_password_toggle = 2131034122;
			
			// aapt resource value: 0x7F05000B
			public const int notification_action_color_filter = 2131034123;
			
			// aapt resource value: 0x7F05000C
			public const int notification_icon_bg_color = 2131034124;
			
			// aapt resource value: 0x7F05000D
			public const int notification_material_background_media_default_color = 2131034125;
			
			// aapt resource value: 0x7F05000E
			public const int primary_text_default_material_dark = 2131034126;
			
			// aapt resource value: 0x7F05000F
			public const int ripple_material_light = 2131034127;
			
			// aapt resource value: 0x7F050010
			public const int secondary_text_default_material_dark = 2131034128;
			
			// aapt resource value: 0x7F050011
			public const int secondary_text_default_material_light = 2131034129;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7F060000
			public const int compat_button_inset_horizontal_material = 2131099648;
			
			// aapt resource value: 0x7F060001
			public const int compat_button_inset_vertical_material = 2131099649;
			
			// aapt resource value: 0x7F060002
			public const int compat_button_padding_horizontal_material = 2131099650;
			
			// aapt resource value: 0x7F060003
			public const int compat_button_padding_vertical_material = 2131099651;
			
			// aapt resource value: 0x7F060004
			public const int compat_control_corner_material = 2131099652;
			
			// aapt resource value: 0x7F060005
			public const int design_appbar_elevation = 2131099653;
			
			// aapt resource value: 0x7F060006
			public const int design_bottom_navigation_active_item_max_width = 2131099654;
			
			// aapt resource value: 0x7F060007
			public const int design_bottom_navigation_active_text_size = 2131099655;
			
			// aapt resource value: 0x7F060008
			public const int design_bottom_navigation_elevation = 2131099656;
			
			// aapt resource value: 0x7F060009
			public const int design_bottom_navigation_height = 2131099657;
			
			// aapt resource value: 0x7F06000A
			public const int design_bottom_navigation_item_max_width = 2131099658;
			
			// aapt resource value: 0x7F06000B
			public const int design_bottom_navigation_item_min_width = 2131099659;
			
			// aapt resource value: 0x7F06000C
			public const int design_bottom_navigation_margin = 2131099660;
			
			// aapt resource value: 0x7F06000D
			public const int design_bottom_navigation_shadow_height = 2131099661;
			
			// aapt resource value: 0x7F06000E
			public const int design_bottom_navigation_text_size = 2131099662;
			
			// aapt resource value: 0x7F06000F
			public const int design_bottom_sheet_modal_elevation = 2131099663;
			
			// aapt resource value: 0x7F060010
			public const int design_bottom_sheet_peek_height_min = 2131099664;
			
			// aapt resource value: 0x7F060011
			public const int design_fab_border_width = 2131099665;
			
			// aapt resource value: 0x7F060012
			public const int design_fab_elevation = 2131099666;
			
			// aapt resource value: 0x7F060013
			public const int design_fab_image_size = 2131099667;
			
			// aapt resource value: 0x7F060014
			public const int design_fab_size_mini = 2131099668;
			
			// aapt resource value: 0x7F060015
			public const int design_fab_size_normal = 2131099669;
			
			// aapt resource value: 0x7F060016
			public const int design_fab_translation_z_pressed = 2131099670;
			
			// aapt resource value: 0x7F060017
			public const int design_navigation_elevation = 2131099671;
			
			// aapt resource value: 0x7F060018
			public const int design_navigation_icon_padding = 2131099672;
			
			// aapt resource value: 0x7F060019
			public const int design_navigation_icon_size = 2131099673;
			
			// aapt resource value: 0x7F06001A
			public const int design_navigation_max_width = 2131099674;
			
			// aapt resource value: 0x7F06001B
			public const int design_navigation_padding_bottom = 2131099675;
			
			// aapt resource value: 0x7F06001C
			public const int design_navigation_separator_vertical_padding = 2131099676;
			
			// aapt resource value: 0x7F06001D
			public const int design_snackbar_action_inline_max_width = 2131099677;
			
			// aapt resource value: 0x7F06001E
			public const int design_snackbar_background_corner_radius = 2131099678;
			
			// aapt resource value: 0x7F06001F
			public const int design_snackbar_elevation = 2131099679;
			
			// aapt resource value: 0x7F060020
			public const int design_snackbar_extra_spacing_horizontal = 2131099680;
			
			// aapt resource value: 0x7F060021
			public const int design_snackbar_max_width = 2131099681;
			
			// aapt resource value: 0x7F060022
			public const int design_snackbar_min_width = 2131099682;
			
			// aapt resource value: 0x7F060023
			public const int design_snackbar_padding_horizontal = 2131099683;
			
			// aapt resource value: 0x7F060024
			public const int design_snackbar_padding_vertical = 2131099684;
			
			// aapt resource value: 0x7F060025
			public const int design_snackbar_padding_vertical_2lines = 2131099685;
			
			// aapt resource value: 0x7F060026
			public const int design_snackbar_text_size = 2131099686;
			
			// aapt resource value: 0x7F060027
			public const int design_tab_max_width = 2131099687;
			
			// aapt resource value: 0x7F060028
			public const int design_tab_scrollable_min_width = 2131099688;
			
			// aapt resource value: 0x7F060029
			public const int design_tab_text_size = 2131099689;
			
			// aapt resource value: 0x7F06002A
			public const int design_tab_text_size_2line = 2131099690;
			
			// aapt resource value: 0x7F06002B
			public const int notification_action_icon_size = 2131099691;
			
			// aapt resource value: 0x7F06002C
			public const int notification_action_text_size = 2131099692;
			
			// aapt resource value: 0x7F06002D
			public const int notification_big_circle_margin = 2131099693;
			
			// aapt resource value: 0x7F06002E
			public const int notification_content_margin_start = 2131099694;
			
			// aapt resource value: 0x7F06002F
			public const int notification_large_icon_height = 2131099695;
			
			// aapt resource value: 0x7F060030
			public const int notification_large_icon_width = 2131099696;
			
			// aapt resource value: 0x7F060031
			public const int notification_main_column_padding_top = 2131099697;
			
			// aapt resource value: 0x7F060032
			public const int notification_media_narrow_margin = 2131099698;
			
			// aapt resource value: 0x7F060033
			public const int notification_right_icon_size = 2131099699;
			
			// aapt resource value: 0x7F060034
			public const int notification_right_side_padding_top = 2131099700;
			
			// aapt resource value: 0x7F060035
			public const int notification_small_icon_background_padding = 2131099701;
			
			// aapt resource value: 0x7F060036
			public const int notification_small_icon_size_as_large = 2131099702;
			
			// aapt resource value: 0x7F060037
			public const int notification_subtext_size = 2131099703;
			
			// aapt resource value: 0x7F060038
			public const int notification_top_pad = 2131099704;
			
			// aapt resource value: 0x7F060039
			public const int notification_top_pad_large_text = 2131099705;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F070000
			public const int avd_hide_password = 2131165184;
			
			// aapt resource value: 0x7F070001
			public const int avd_show_password = 2131165185;
			
			// aapt resource value: 0x7F070002
			public const int bethanylogo = 2131165186;
			
			// aapt resource value: 0x7F070003
			public const int bethanylogowithborder = 2131165187;
			
			// aapt resource value: 0x7F070004
			public const int carousel1 = 2131165188;
			
			// aapt resource value: 0x7F070005
			public const int carousel2 = 2131165189;
			
			// aapt resource value: 0x7F070006
			public const int carousel3 = 2131165190;
			
			// aapt resource value: 0x7F070007
			public const int darktexture = 2131165191;
			
			// aapt resource value: 0x7F070008
			public const int design_bottom_navigation_item_background = 2131165192;
			
			// aapt resource value: 0x7F070009
			public const int design_fab_background = 2131165193;
			
			// aapt resource value: 0x7F07000A
			public const int design_ic_visibility = 2131165194;
			
			// aapt resource value: 0x7F07000B
			public const int design_ic_visibility_off = 2131165195;
			
			// aapt resource value: 0x7F07000C
			public const int design_password_eye = 2131165196;
			
			// aapt resource value: 0x7F07000D
			public const int design_snackbar_background = 2131165197;
			
			// aapt resource value: 0x7F07000E
			public const int header1 = 2131165198;
			
			// aapt resource value: 0x7F07000F
			public const int ic_cart = 2131165199;
			
			// aapt resource value: 0x7F070010
			public const int ic_contact = 2131165200;
			
			// aapt resource value: 0x7F070011
			public const int ic_errorstatus = 2131165201;
			
			// aapt resource value: 0x7F070012
			public const int ic_home = 2131165202;
			
			// aapt resource value: 0x7F070013
			public const int ic_logout = 2131165203;
			
			// aapt resource value: 0x7F070014
			public const int ic_pies = 2131165204;
			
			// aapt resource value: 0x7F070015
			public const int ic_successstatus = 2131165205;
			
			// aapt resource value: 0x7F070016
			public const int navigation_empty_icon = 2131165206;
			
			// aapt resource value: 0x7F070017
			public const int notification_action_background = 2131165207;
			
			// aapt resource value: 0x7F070018
			public const int notification_bg = 2131165208;
			
			// aapt resource value: 0x7F070019
			public const int notification_bg_low = 2131165209;
			
			// aapt resource value: 0x7F07001A
			public const int notification_bg_low_normal = 2131165210;
			
			// aapt resource value: 0x7F07001B
			public const int notification_bg_low_pressed = 2131165211;
			
			// aapt resource value: 0x7F07001C
			public const int notification_bg_normal = 2131165212;
			
			// aapt resource value: 0x7F07001D
			public const int notification_bg_normal_pressed = 2131165213;
			
			// aapt resource value: 0x7F07001E
			public const int notification_icon_background = 2131165214;
			
			// aapt resource value: 0x7F07001F
			public const int notification_template_icon_bg = 2131165215;
			
			// aapt resource value: 0x7F070020
			public const int notification_template_icon_low_bg = 2131165216;
			
			// aapt resource value: 0x7F070021
			public const int notification_tile_bg = 2131165217;
			
			// aapt resource value: 0x7F070022
			public const int notify_panel_notification_icon_bg = 2131165218;
			
			// aapt resource value: 0x7F070023
			public const int pattern = 2131165219;
			
			// aapt resource value: 0x7F070024
			public const int patternwide = 2131165220;
			
			// aapt resource value: 0x7F070025
			public const int roundedbg = 2131165221;
			
			// aapt resource value: 0x7F070026
			public const int roundedbgdark = 2131165222;
			
			// aapt resource value: 0x7F070027
			public const int splash = 2131165223;
			
			// aapt resource value: 0x7F070028
			public const int splash_drawable = 2131165224;
			
			// aapt resource value: 0x7F070029
			public const int springsale = 2131165225;
			
			// aapt resource value: 0x7F07002A
			public const int whitewood = 2131165226;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F080000
			public const int action0 = 2131230720;
			
			// aapt resource value: 0x7F080001
			public const int actions = 2131230721;
			
			// aapt resource value: 0x7F080002
			public const int action_container = 2131230722;
			
			// aapt resource value: 0x7F080003
			public const int action_divider = 2131230723;
			
			// aapt resource value: 0x7F080004
			public const int action_image = 2131230724;
			
			// aapt resource value: 0x7F080005
			public const int action_text = 2131230725;
			
			// aapt resource value: 0x7F080006
			public const int all = 2131230726;
			
			// aapt resource value: 0x7F080007
			public const int async = 2131230727;
			
			// aapt resource value: 0x7F080008
			public const int auto = 2131230728;
			
			// aapt resource value: 0x7F080009
			public const int blocking = 2131230729;
			
			// aapt resource value: 0x7F08000A
			public const int bottom = 2131230730;
			
			// aapt resource value: 0x7F08000B
			public const int cancel_action = 2131230731;
			
			// aapt resource value: 0x7F08000C
			public const int center = 2131230732;
			
			// aapt resource value: 0x7F08000D
			public const int center_horizontal = 2131230733;
			
			// aapt resource value: 0x7F08000E
			public const int center_vertical = 2131230734;
			
			// aapt resource value: 0x7F08000F
			public const int chronometer = 2131230735;
			
			// aapt resource value: 0x7F080010
			public const int clip_horizontal = 2131230736;
			
			// aapt resource value: 0x7F080011
			public const int clip_vertical = 2131230737;
			
			// aapt resource value: 0x7F080012
			public const int container = 2131230738;
			
			// aapt resource value: 0x7F080013
			public const int coordinator = 2131230739;
			
			// aapt resource value: 0x7F080014
			public const int design_bottom_sheet = 2131230740;
			
			// aapt resource value: 0x7F080015
			public const int design_menu_item_action_area_stub = 2131230741;
			
			// aapt resource value: 0x7F080016
			public const int design_menu_item_text = 2131230742;
			
			// aapt resource value: 0x7F080017
			public const int design_navigation_view = 2131230743;
			
			// aapt resource value: 0x7F080018
			public const int end = 2131230744;
			
			// aapt resource value: 0x7F080019
			public const int end_padder = 2131230745;
			
			// aapt resource value: 0x7F08001A
			public const int enterAlways = 2131230746;
			
			// aapt resource value: 0x7F08001B
			public const int enterAlwaysCollapsed = 2131230747;
			
			// aapt resource value: 0x7F08001C
			public const int exitUntilCollapsed = 2131230748;
			
			// aapt resource value: 0x7F08001D
			public const int fill = 2131230749;
			
			// aapt resource value: 0x7F08001E
			public const int fill_horizontal = 2131230750;
			
			// aapt resource value: 0x7F08001F
			public const int fill_vertical = 2131230751;
			
			// aapt resource value: 0x7F080020
			public const int @fixed = 2131230752;
			
			// aapt resource value: 0x7F080021
			public const int forever = 2131230753;
			
			// aapt resource value: 0x7F080022
			public const int ghost_view = 2131230754;
			
			// aapt resource value: 0x7F080023
			public const int icon = 2131230755;
			
			// aapt resource value: 0x7F080024
			public const int icon_group = 2131230756;
			
			// aapt resource value: 0x7F080025
			public const int info = 2131230757;
			
			// aapt resource value: 0x7F080026
			public const int italic = 2131230758;
			
			// aapt resource value: 0x7F080027
			public const int largeLabel = 2131230759;
			
			// aapt resource value: 0x7F080028
			public const int left = 2131230760;
			
			// aapt resource value: 0x7F080029
			public const int line1 = 2131230761;
			
			// aapt resource value: 0x7F08002A
			public const int line3 = 2131230762;
			
			// aapt resource value: 0x7F08002B
			public const int loadingImage = 2131230763;
			
			// aapt resource value: 0x7F08002C
			public const int loadingProgressBar = 2131230764;
			
			// aapt resource value: 0x7F08002D
			public const int loadingProgressWheel = 2131230765;
			
			// aapt resource value: 0x7F08002E
			public const int masked = 2131230766;
			
			// aapt resource value: 0x7F08002F
			public const int media_actions = 2131230767;
			
			// aapt resource value: 0x7F080030
			public const int mini = 2131230768;
			
			// aapt resource value: 0x7F080031
			public const int multiply = 2131230769;
			
			// aapt resource value: 0x7F080032
			public const int navigation_header_container = 2131230770;
			
			// aapt resource value: 0x7F080033
			public const int none = 2131230771;
			
			// aapt resource value: 0x7F080034
			public const int normal = 2131230772;
			
			// aapt resource value: 0x7F080035
			public const int notification_background = 2131230773;
			
			// aapt resource value: 0x7F080036
			public const int notification_main_column = 2131230774;
			
			// aapt resource value: 0x7F080037
			public const int notification_main_column_container = 2131230775;
			
			// aapt resource value: 0x7F080038
			public const int parallax = 2131230776;
			
			// aapt resource value: 0x7F080039
			public const int parent_matrix = 2131230777;
			
			// aapt resource value: 0x7F08003A
			public const int pin = 2131230778;
			
			// aapt resource value: 0x7F08003B
			public const int right = 2131230779;
			
			// aapt resource value: 0x7F08003C
			public const int right_icon = 2131230780;
			
			// aapt resource value: 0x7F08003D
			public const int right_side = 2131230781;
			
			// aapt resource value: 0x7F08003E
			public const int save_image_matrix = 2131230782;
			
			// aapt resource value: 0x7F08003F
			public const int save_non_transition_alpha = 2131230783;
			
			// aapt resource value: 0x7F080040
			public const int save_scale_type = 2131230784;
			
			// aapt resource value: 0x7F080041
			public const int screen = 2131230785;
			
			// aapt resource value: 0x7F080042
			public const int scroll = 2131230786;
			
			// aapt resource value: 0x7F080043
			public const int scrollable = 2131230787;
			
			// aapt resource value: 0x7F080044
			public const int sliding_tabs = 2131230788;
			
			// aapt resource value: 0x7F080045
			public const int smallLabel = 2131230789;
			
			// aapt resource value: 0x7F080046
			public const int snackbar_action = 2131230790;
			
			// aapt resource value: 0x7F080047
			public const int snackbar_text = 2131230791;
			
			// aapt resource value: 0x7F080048
			public const int snap = 2131230792;
			
			// aapt resource value: 0x7F080049
			public const int src_atop = 2131230793;
			
			// aapt resource value: 0x7F08004A
			public const int src_in = 2131230794;
			
			// aapt resource value: 0x7F08004B
			public const int src_over = 2131230795;
			
			// aapt resource value: 0x7F08004C
			public const int start = 2131230796;
			
			// aapt resource value: 0x7F08004D
			public const int status_bar_latest_event_content = 2131230797;
			
			// aapt resource value: 0x7F08004E
			public const int tag_transition_group = 2131230798;
			
			// aapt resource value: 0x7F08004F
			public const int text = 2131230799;
			
			// aapt resource value: 0x7F080050
			public const int text2 = 2131230800;
			
			// aapt resource value: 0x7F080051
			public const int textinput_counter = 2131230801;
			
			// aapt resource value: 0x7F080052
			public const int textinput_error = 2131230802;
			
			// aapt resource value: 0x7F080053
			public const int textViewStatus = 2131230803;
			
			// aapt resource value: 0x7F080054
			public const int text_input_password_toggle = 2131230804;
			
			// aapt resource value: 0x7F080055
			public const int time = 2131230805;
			
			// aapt resource value: 0x7F080056
			public const int title = 2131230806;
			
			// aapt resource value: 0x7F080057
			public const int toolbar = 2131230807;
			
			// aapt resource value: 0x7F080058
			public const int top = 2131230808;
			
			// aapt resource value: 0x7F080059
			public const int touch_outside = 2131230809;
			
			// aapt resource value: 0x7F08005A
			public const int transition_current_scene = 2131230810;
			
			// aapt resource value: 0x7F08005B
			public const int transition_layout_save = 2131230811;
			
			// aapt resource value: 0x7F08005C
			public const int transition_position = 2131230812;
			
			// aapt resource value: 0x7F08005D
			public const int transition_scene_layoutid_cache = 2131230813;
			
			// aapt resource value: 0x7F08005E
			public const int transition_transform = 2131230814;
			
			// aapt resource value: 0x7F08005F
			public const int view_offset_helper = 2131230815;
			
			// aapt resource value: 0x7F080060
			public const int visible = 2131230816;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7F090000
			public const int app_bar_elevation_anim_duration = 2131296256;
			
			// aapt resource value: 0x7F090001
			public const int bottom_sheet_slide_duration = 2131296257;
			
			// aapt resource value: 0x7F090002
			public const int cancel_button_image_alpha = 2131296258;
			
			// aapt resource value: 0x7F090003
			public const int design_snackbar_text_max_lines = 2131296259;
			
			// aapt resource value: 0x7F090004
			public const int hide_password_duration = 2131296260;
			
			// aapt resource value: 0x7F090005
			public const int show_password_duration = 2131296261;
			
			// aapt resource value: 0x7F090006
			public const int status_bar_notification_info_maxnum = 2131296262;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F0A0000
			public const int design_bottom_navigation_item = 2131361792;
			
			// aapt resource value: 0x7F0A0001
			public const int design_bottom_sheet_dialog = 2131361793;
			
			// aapt resource value: 0x7F0A0002
			public const int design_layout_snackbar = 2131361794;
			
			// aapt resource value: 0x7F0A0003
			public const int design_layout_snackbar_include = 2131361795;
			
			// aapt resource value: 0x7F0A0004
			public const int design_layout_tab_icon = 2131361796;
			
			// aapt resource value: 0x7F0A0005
			public const int design_layout_tab_text = 2131361797;
			
			// aapt resource value: 0x7F0A0006
			public const int design_menu_item_action_area = 2131361798;
			
			// aapt resource value: 0x7F0A0007
			public const int design_navigation_item = 2131361799;
			
			// aapt resource value: 0x7F0A0008
			public const int design_navigation_item_header = 2131361800;
			
			// aapt resource value: 0x7F0A0009
			public const int design_navigation_item_separator = 2131361801;
			
			// aapt resource value: 0x7F0A000A
			public const int design_navigation_item_subheader = 2131361802;
			
			// aapt resource value: 0x7F0A000B
			public const int design_navigation_menu = 2131361803;
			
			// aapt resource value: 0x7F0A000C
			public const int design_navigation_menu_item = 2131361804;
			
			// aapt resource value: 0x7F0A000D
			public const int design_text_input_password_icon = 2131361805;
			
			// aapt resource value: 0x7F0A000E
			public const int loading = 2131361806;
			
			// aapt resource value: 0x7F0A000F
			public const int loadingimage = 2131361807;
			
			// aapt resource value: 0x7F0A0010
			public const int loadingprogress = 2131361808;
			
			// aapt resource value: 0x7F0A0011
			public const int notification_action = 2131361809;
			
			// aapt resource value: 0x7F0A0012
			public const int notification_action_tombstone = 2131361810;
			
			// aapt resource value: 0x7F0A0013
			public const int notification_media_action = 2131361811;
			
			// aapt resource value: 0x7F0A0014
			public const int notification_media_cancel_action = 2131361812;
			
			// aapt resource value: 0x7F0A0015
			public const int notification_template_big_media = 2131361813;
			
			// aapt resource value: 0x7F0A0016
			public const int notification_template_big_media_custom = 2131361814;
			
			// aapt resource value: 0x7F0A0017
			public const int notification_template_big_media_narrow = 2131361815;
			
			// aapt resource value: 0x7F0A0018
			public const int notification_template_big_media_narrow_custom = 2131361816;
			
			// aapt resource value: 0x7F0A0019
			public const int notification_template_custom_big = 2131361817;
			
			// aapt resource value: 0x7F0A001A
			public const int notification_template_icon_group = 2131361818;
			
			// aapt resource value: 0x7F0A001B
			public const int notification_template_lines_media = 2131361819;
			
			// aapt resource value: 0x7F0A001C
			public const int notification_template_media = 2131361820;
			
			// aapt resource value: 0x7F0A001D
			public const int notification_template_media_custom = 2131361821;
			
			// aapt resource value: 0x7F0A001E
			public const int notification_template_part_chronometer = 2131361822;
			
			// aapt resource value: 0x7F0A001F
			public const int notification_template_part_time = 2131361823;
			
			// aapt resource value: 0x7F0A0020
			public const int Tabbar = 2131361824;
			
			// aapt resource value: 0x7F0A0021
			public const int Toolbar = 2131361825;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7F0B0000
			public const int ic_launcher = 2131427328;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F0C0000
			public const int appbar_scrolling_view_behavior = 2131492864;
			
			// aapt resource value: 0x7F0C0001
			public const int bottom_sheet_behavior = 2131492865;
			
			// aapt resource value: 0x7F0C0002
			public const int character_counter_pattern = 2131492866;
			
			// aapt resource value: 0x7F0C0003
			public const int library_name = 2131492867;
			
			// aapt resource value: 0x7F0C0004
			public const int password_toggle_content_description = 2131492868;
			
			// aapt resource value: 0x7F0C0005
			public const int path_password_eye = 2131492869;
			
			// aapt resource value: 0x7F0C0006
			public const int path_password_eye_mask_strike_through = 2131492870;
			
			// aapt resource value: 0x7F0C0007
			public const int path_password_eye_mask_visible = 2131492871;
			
			// aapt resource value: 0x7F0C0008
			public const int path_password_strike_through = 2131492872;
			
			// aapt resource value: 0x7F0C0009
			public const int status_bar_notification_info_overflow = 2131492873;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F0D0000
			public const int Animation_Design_BottomSheetDialog = 2131558400;
			
			// aapt resource value: 0x7F0D0001
			public const int AppCompatDialogStyle = 2131558401;
			
			// aapt resource value: 0x7F0D0002
			public const int Base_V14_Widget_Design_AppBarLayout = 2131558402;
			
			// aapt resource value: 0x7F0D0003
			public const int Base_V21_Widget_Design_AppBarLayout = 2131558403;
			
			// aapt resource value: 0x7F0D0004
			public const int Base_V26_Widget_Design_AppBarLayout = 2131558404;
			
			// aapt resource value: 0x7F0D0005
			public const int Base_Widget_Design_AppBarLayout = 2131558405;
			
			// aapt resource value: 0x7F0D0006
			public const int Base_Widget_Design_TabLayout = 2131558406;
			
			// aapt resource value: 0x7F0D0007
			public const int MainTheme = 2131558407;
			
			// aapt resource value: 0x7F0D0008
			public const int MainTheme_Base = 2131558408;
			
			// aapt resource value: 0x7F0D0009
			public const int SplashTheme = 2131558409;
			
			// aapt resource value: 0x7F0D000A
			public const int TextAppearance_Compat_Notification = 2131558410;
			
			// aapt resource value: 0x7F0D000B
			public const int TextAppearance_Compat_Notification_Info = 2131558411;
			
			// aapt resource value: 0x7F0D000C
			public const int TextAppearance_Compat_Notification_Info_Media = 2131558412;
			
			// aapt resource value: 0x7F0D000D
			public const int TextAppearance_Compat_Notification_Line2 = 2131558413;
			
			// aapt resource value: 0x7F0D000E
			public const int TextAppearance_Compat_Notification_Line2_Media = 2131558414;
			
			// aapt resource value: 0x7F0D000F
			public const int TextAppearance_Compat_Notification_Media = 2131558415;
			
			// aapt resource value: 0x7F0D0010
			public const int TextAppearance_Compat_Notification_Time = 2131558416;
			
			// aapt resource value: 0x7F0D0011
			public const int TextAppearance_Compat_Notification_Time_Media = 2131558417;
			
			// aapt resource value: 0x7F0D0012
			public const int TextAppearance_Compat_Notification_Title = 2131558418;
			
			// aapt resource value: 0x7F0D0013
			public const int TextAppearance_Compat_Notification_Title_Media = 2131558419;
			
			// aapt resource value: 0x7F0D0014
			public const int TextAppearance_Design_CollapsingToolbar_Expanded = 2131558420;
			
			// aapt resource value: 0x7F0D0015
			public const int TextAppearance_Design_Counter = 2131558421;
			
			// aapt resource value: 0x7F0D0016
			public const int TextAppearance_Design_Counter_Overflow = 2131558422;
			
			// aapt resource value: 0x7F0D0017
			public const int TextAppearance_Design_Error = 2131558423;
			
			// aapt resource value: 0x7F0D0018
			public const int TextAppearance_Design_Hint = 2131558424;
			
			// aapt resource value: 0x7F0D0019
			public const int TextAppearance_Design_Snackbar_Message = 2131558425;
			
			// aapt resource value: 0x7F0D001A
			public const int TextAppearance_Design_Tab = 2131558426;
			
			// aapt resource value: 0x7F0D001B
			public const int Theme_Design = 2131558427;
			
			// aapt resource value: 0x7F0D001C
			public const int Theme_Design_BottomSheetDialog = 2131558428;
			
			// aapt resource value: 0x7F0D001D
			public const int Theme_Design_Light = 2131558429;
			
			// aapt resource value: 0x7F0D001E
			public const int Theme_Design_Light_BottomSheetDialog = 2131558430;
			
			// aapt resource value: 0x7F0D001F
			public const int Theme_Design_Light_NoActionBar = 2131558431;
			
			// aapt resource value: 0x7F0D0020
			public const int Theme_Design_NoActionBar = 2131558432;
			
			// aapt resource value: 0x7F0D0021
			public const int Widget_Compat_NotificationActionContainer = 2131558433;
			
			// aapt resource value: 0x7F0D0022
			public const int Widget_Compat_NotificationActionText = 2131558434;
			
			// aapt resource value: 0x7F0D0023
			public const int Widget_Design_AppBarLayout = 2131558435;
			
			// aapt resource value: 0x7F0D0024
			public const int Widget_Design_BottomNavigationView = 2131558436;
			
			// aapt resource value: 0x7F0D0025
			public const int Widget_Design_BottomSheet_Modal = 2131558437;
			
			// aapt resource value: 0x7F0D0026
			public const int Widget_Design_CollapsingToolbar = 2131558438;
			
			// aapt resource value: 0x7F0D0027
			public const int Widget_Design_CoordinatorLayout = 2131558439;
			
			// aapt resource value: 0x7F0D0028
			public const int Widget_Design_FloatingActionButton = 2131558440;
			
			// aapt resource value: 0x7F0D0029
			public const int Widget_Design_NavigationView = 2131558441;
			
			// aapt resource value: 0x7F0D002A
			public const int Widget_Design_ScrimInsetsFrameLayout = 2131558442;
			
			// aapt resource value: 0x7F0D002B
			public const int Widget_Design_Snackbar = 2131558443;
			
			// aapt resource value: 0x7F0D002C
			public const int Widget_Design_TabLayout = 2131558444;
			
			// aapt resource value: 0x7F0D002D
			public const int Widget_Design_TextInputLayout = 2131558445;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			// aapt resource value: { 0x10100D4,0x1010540,0x101048F,0x7F03001D,0x7F030020 }
			public static int[] AppBarLayout = new int[] {
					16842964,
					16844096,
					16843919,
					2130903069,
					2130903072};
			
			// aapt resource value: { 0x7F030052,0x7F030053 }
			public static int[] AppBarLayoutStates = new int[] {
					2130903122,
					2130903123};
			
			// aapt resource value: 0
			public const int AppBarLayoutStates_state_collapsed = 0;
			
			// aapt resource value: 1
			public const int AppBarLayoutStates_state_collapsible = 1;
			
			// aapt resource value: 0
			public const int AppBarLayout_android_background = 0;
			
			// aapt resource value: 1
			public const int AppBarLayout_android_keyboardNavigationCluster = 1;
			
			// aapt resource value: 2
			public const int AppBarLayout_android_touchscreenBlocksFocus = 2;
			
			// aapt resource value: 3
			public const int AppBarLayout_elevation = 3;
			
			// aapt resource value: 4
			public const int AppBarLayout_expanded = 4;
			
			// aapt resource value: { 0x7F030045,0x7F030046 }
			public static int[] AppBarLayout_Layout = new int[] {
					2130903109,
					2130903110};
			
			// aapt resource value: 0
			public const int AppBarLayout_Layout_layout_scrollFlags = 0;
			
			// aapt resource value: 1
			public const int AppBarLayout_Layout_layout_scrollInterpolator = 1;
			
			// aapt resource value: { 0x7F03001D,0x7F030038,0x7F030039,0x7F03003B,0x7F030048 }
			public static int[] BottomNavigationView = new int[] {
					2130903069,
					2130903096,
					2130903097,
					2130903099,
					2130903112};
			
			// aapt resource value: 0
			public const int BottomNavigationView_elevation = 0;
			
			// aapt resource value: 1
			public const int BottomNavigationView_itemBackground = 1;
			
			// aapt resource value: 2
			public const int BottomNavigationView_itemIconTint = 2;
			
			// aapt resource value: 3
			public const int BottomNavigationView_itemTextColor = 3;
			
			// aapt resource value: 4
			public const int BottomNavigationView_menu = 4;
			
			// aapt resource value: { 0x7F03000F,0x7F030011,0x7F030012 }
			public static int[] BottomSheetBehavior_Layout = new int[] {
					2130903055,
					2130903057,
					2130903058};
			
			// aapt resource value: 0
			public const int BottomSheetBehavior_Layout_behavior_hideable = 0;
			
			// aapt resource value: 1
			public const int BottomSheetBehavior_Layout_behavior_peekHeight = 1;
			
			// aapt resource value: 2
			public const int BottomSheetBehavior_Layout_behavior_skipCollapsed = 2;
			
			// aapt resource value: { 0x7F030016,0x7F030017,0x7F030018,0x7F030021,0x7F030022,0x7F030023,0x7F030024,0x7F030025,0x7F030026,0x7F030027,0x7F030050,0x7F030051,0x7F030055,0x7F030067,0x7F030068,0x7F030069 }
			public static int[] CollapsingToolbarLayout = new int[] {
					2130903062,
					2130903063,
					2130903064,
					2130903073,
					2130903074,
					2130903075,
					2130903076,
					2130903077,
					2130903078,
					2130903079,
					2130903120,
					2130903121,
					2130903125,
					2130903143,
					2130903144,
					2130903145};
			
			// aapt resource value: 0
			public const int CollapsingToolbarLayout_collapsedTitleGravity = 0;
			
			// aapt resource value: 1
			public const int CollapsingToolbarLayout_collapsedTitleTextAppearance = 1;
			
			// aapt resource value: 2
			public const int CollapsingToolbarLayout_contentScrim = 2;
			
			// aapt resource value: 3
			public const int CollapsingToolbarLayout_expandedTitleGravity = 3;
			
			// aapt resource value: 4
			public const int CollapsingToolbarLayout_expandedTitleMargin = 4;
			
			// aapt resource value: 5
			public const int CollapsingToolbarLayout_expandedTitleMarginBottom = 5;
			
			// aapt resource value: 6
			public const int CollapsingToolbarLayout_expandedTitleMarginEnd = 6;
			
			// aapt resource value: 7
			public const int CollapsingToolbarLayout_expandedTitleMarginStart = 7;
			
			// aapt resource value: 8
			public const int CollapsingToolbarLayout_expandedTitleMarginTop = 8;
			
			// aapt resource value: 9
			public const int CollapsingToolbarLayout_expandedTitleTextAppearance = 9;
			
			// aapt resource value: { 0x7F030040,0x7F030041 }
			public static int[] CollapsingToolbarLayout_Layout = new int[] {
					2130903104,
					2130903105};
			
			// aapt resource value: 0
			public const int CollapsingToolbarLayout_Layout_layout_collapseMode = 0;
			
			// aapt resource value: 1
			public const int CollapsingToolbarLayout_Layout_layout_collapseParallaxMultiplier = 1;
			
			// aapt resource value: 10
			public const int CollapsingToolbarLayout_scrimAnimationDuration = 10;
			
			// aapt resource value: 11
			public const int CollapsingToolbarLayout_scrimVisibleHeightTrigger = 11;
			
			// aapt resource value: 12
			public const int CollapsingToolbarLayout_statusBarScrim = 12;
			
			// aapt resource value: 13
			public const int CollapsingToolbarLayout_title = 13;
			
			// aapt resource value: 14
			public const int CollapsingToolbarLayout_titleEnabled = 14;
			
			// aapt resource value: 15
			public const int CollapsingToolbarLayout_toolbarId = 15;
			
			// aapt resource value: { 0x7F03003C,0x7F030054 }
			public static int[] CoordinatorLayout = new int[] {
					2130903100,
					2130903124};
			
			// aapt resource value: 0
			public const int CoordinatorLayout_keylines = 0;
			
			// aapt resource value: { 0x10100B3,0x7F03003D,0x7F03003E,0x7F03003F,0x7F030042,0x7F030043,0x7F030044 }
			public static int[] CoordinatorLayout_Layout = new int[] {
					16842931,
					2130903101,
					2130903102,
					2130903103,
					2130903106,
					2130903107,
					2130903108};
			
			// aapt resource value: 0
			public const int CoordinatorLayout_Layout_android_layout_gravity = 0;
			
			// aapt resource value: 1
			public const int CoordinatorLayout_Layout_layout_anchor = 1;
			
			// aapt resource value: 2
			public const int CoordinatorLayout_Layout_layout_anchorGravity = 2;
			
			// aapt resource value: 3
			public const int CoordinatorLayout_Layout_layout_behavior = 3;
			
			// aapt resource value: 4
			public const int CoordinatorLayout_Layout_layout_dodgeInsetEdges = 4;
			
			// aapt resource value: 5
			public const int CoordinatorLayout_Layout_layout_insetEdge = 5;
			
			// aapt resource value: 6
			public const int CoordinatorLayout_Layout_layout_keyline = 6;
			
			// aapt resource value: 1
			public const int CoordinatorLayout_statusBarBackground = 1;
			
			// aapt resource value: { 0x7F030014,0x7F030015,0x7F030066 }
			public static int[] DesignTheme = new int[] {
					2130903060,
					2130903061,
					2130903142};
			
			// aapt resource value: 0
			public const int DesignTheme_bottomSheetDialogTheme = 0;
			
			// aapt resource value: 1
			public const int DesignTheme_bottomSheetStyle = 1;
			
			// aapt resource value: 2
			public const int DesignTheme_textColorError = 2;
			
			// aapt resource value: { 0x7F03000C,0x7F03000D,0x7F030013,0x7F03001D,0x7F030028,0x7F03004E,0x7F03004F,0x7F03006A }
			public static int[] FloatingActionButton = new int[] {
					2130903052,
					2130903053,
					2130903059,
					2130903069,
					2130903080,
					2130903118,
					2130903119,
					2130903146};
			
			// aapt resource value: 0
			public const int FloatingActionButton_backgroundTint = 0;
			
			// aapt resource value: 1
			public const int FloatingActionButton_backgroundTintMode = 1;
			
			// aapt resource value: { 0x7F03000E }
			public static int[] FloatingActionButton_Behavior_Layout = new int[] {
					2130903054};
			
			// aapt resource value: 0
			public const int FloatingActionButton_Behavior_Layout_behavior_autoHide = 0;
			
			// aapt resource value: 2
			public const int FloatingActionButton_borderWidth = 2;
			
			// aapt resource value: 3
			public const int FloatingActionButton_elevation = 3;
			
			// aapt resource value: 4
			public const int FloatingActionButton_fabSize = 4;
			
			// aapt resource value: 5
			public const int FloatingActionButton_pressedTranslationZ = 5;
			
			// aapt resource value: 6
			public const int FloatingActionButton_rippleColor = 6;
			
			// aapt resource value: 7
			public const int FloatingActionButton_useCompatPadding = 7;
			
			// aapt resource value: { 0x7F03002A,0x7F03002B,0x7F03002C,0x7F03002D,0x7F03002E,0x7F03002F }
			public static int[] FontFamily = new int[] {
					2130903082,
					2130903083,
					2130903084,
					2130903085,
					2130903086,
					2130903087};
			
			// aapt resource value: { 0x1010532,0x101053F,0x1010533,0x7F030029,0x7F030030,0x7F030031 }
			public static int[] FontFamilyFont = new int[] {
					16844082,
					16844095,
					16844083,
					2130903081,
					2130903088,
					2130903089};
			
			// aapt resource value: 0
			public const int FontFamilyFont_android_font = 0;
			
			// aapt resource value: 1
			public const int FontFamilyFont_android_fontStyle = 1;
			
			// aapt resource value: 2
			public const int FontFamilyFont_android_fontWeight = 2;
			
			// aapt resource value: 3
			public const int FontFamilyFont_font = 3;
			
			// aapt resource value: 4
			public const int FontFamilyFont_fontStyle = 4;
			
			// aapt resource value: 5
			public const int FontFamilyFont_fontWeight = 5;
			
			// aapt resource value: 0
			public const int FontFamily_fontProviderAuthority = 0;
			
			// aapt resource value: 1
			public const int FontFamily_fontProviderCerts = 1;
			
			// aapt resource value: 2
			public const int FontFamily_fontProviderFetchStrategy = 2;
			
			// aapt resource value: 3
			public const int FontFamily_fontProviderFetchTimeout = 3;
			
			// aapt resource value: 4
			public const int FontFamily_fontProviderPackage = 4;
			
			// aapt resource value: 5
			public const int FontFamily_fontProviderQuery = 5;
			
			// aapt resource value: { 0x1010109,0x1010200,0x7F030032 }
			public static int[] ForegroundLinearLayout = new int[] {
					16843017,
					16843264,
					2130903090};
			
			// aapt resource value: 0
			public const int ForegroundLinearLayout_android_foreground = 0;
			
			// aapt resource value: 1
			public const int ForegroundLinearLayout_android_foregroundGravity = 1;
			
			// aapt resource value: 2
			public const int ForegroundLinearLayout_foregroundInsidePadding = 2;
			
			// aapt resource value: { 0x10100D4,0x10100DD,0x101011F,0x7F03001D,0x7F030033,0x7F030038,0x7F030039,0x7F03003A,0x7F03003B,0x7F030048 }
			public static int[] NavigationView = new int[] {
					16842964,
					16842973,
					16843039,
					2130903069,
					2130903091,
					2130903096,
					2130903097,
					2130903098,
					2130903099,
					2130903112};
			
			// aapt resource value: 0
			public const int NavigationView_android_background = 0;
			
			// aapt resource value: 1
			public const int NavigationView_android_fitsSystemWindows = 1;
			
			// aapt resource value: 2
			public const int NavigationView_android_maxWidth = 2;
			
			// aapt resource value: 3
			public const int NavigationView_elevation = 3;
			
			// aapt resource value: 4
			public const int NavigationView_headerLayout = 4;
			
			// aapt resource value: 5
			public const int NavigationView_itemBackground = 5;
			
			// aapt resource value: 6
			public const int NavigationView_itemIconTint = 6;
			
			// aapt resource value: 7
			public const int NavigationView_itemTextAppearance = 7;
			
			// aapt resource value: 8
			public const int NavigationView_itemTextColor = 8;
			
			// aapt resource value: 9
			public const int NavigationView_menu = 9;
			
			// aapt resource value: { 0x7F030000,0x7F030001,0x7F030002,0x7F030003,0x7F030004,0x7F030005,0x7F030006,0x7F030007,0x7F030008,0x7F030009,0x7F03000A,0x7F03000B }
			public static int[] ProgressWheel = new int[] {
					2130903040,
					2130903041,
					2130903042,
					2130903043,
					2130903044,
					2130903045,
					2130903046,
					2130903047,
					2130903048,
					2130903049,
					2130903050,
					2130903051};
			
			// aapt resource value: 0
			public const int ProgressWheel_ahBarColor = 0;
			
			// aapt resource value: 1
			public const int ProgressWheel_ahBarLength = 1;
			
			// aapt resource value: 2
			public const int ProgressWheel_ahBarWidth = 2;
			
			// aapt resource value: 3
			public const int ProgressWheel_ahCircleColor = 3;
			
			// aapt resource value: 4
			public const int ProgressWheel_ahDelayMillis = 4;
			
			// aapt resource value: 5
			public const int ProgressWheel_ahRadius = 5;
			
			// aapt resource value: 6
			public const int ProgressWheel_ahRimColor = 6;
			
			// aapt resource value: 7
			public const int ProgressWheel_ahRimWidth = 7;
			
			// aapt resource value: 8
			public const int ProgressWheel_ahSpinSpeed = 8;
			
			// aapt resource value: 9
			public const int ProgressWheel_ahText = 9;
			
			// aapt resource value: 10
			public const int ProgressWheel_ahTextColor = 10;
			
			// aapt resource value: 11
			public const int ProgressWheel_ahTextSize = 11;
			
			// aapt resource value: { 0x7F030037 }
			public static int[] ScrimInsetsFrameLayout = new int[] {
					2130903095};
			
			// aapt resource value: 0
			public const int ScrimInsetsFrameLayout_insetForeground = 0;
			
			// aapt resource value: { 0x7F030010 }
			public static int[] ScrollingViewBehavior_Layout = new int[] {
					2130903056};
			
			// aapt resource value: 0
			public const int ScrollingViewBehavior_Layout_behavior_overlapTop = 0;
			
			// aapt resource value: { 0x101011F,0x7F03001D,0x7F030047 }
			public static int[] SnackbarLayout = new int[] {
					16843039,
					2130903069,
					2130903111};
			
			// aapt resource value: 0
			public const int SnackbarLayout_android_maxWidth = 0;
			
			// aapt resource value: 1
			public const int SnackbarLayout_elevation = 1;
			
			// aapt resource value: 2
			public const int SnackbarLayout_maxActionInlineWidth = 2;
			
			// aapt resource value: { 0x1010002,0x10100F2,0x101014F }
			public static int[] TabItem = new int[] {
					16842754,
					16842994,
					16843087};
			
			// aapt resource value: 0
			public const int TabItem_android_icon = 0;
			
			// aapt resource value: 1
			public const int TabItem_android_layout = 1;
			
			// aapt resource value: 2
			public const int TabItem_android_text = 2;
			
			// aapt resource value: { 0x7F030056,0x7F030057,0x7F030058,0x7F030059,0x7F03005A,0x7F03005B,0x7F03005C,0x7F03005D,0x7F03005E,0x7F03005F,0x7F030060,0x7F030061,0x7F030062,0x7F030063,0x7F030064,0x7F030065 }
			public static int[] TabLayout = new int[] {
					2130903126,
					2130903127,
					2130903128,
					2130903129,
					2130903130,
					2130903131,
					2130903132,
					2130903133,
					2130903134,
					2130903135,
					2130903136,
					2130903137,
					2130903138,
					2130903139,
					2130903140,
					2130903141};
			
			// aapt resource value: 0
			public const int TabLayout_tabBackground = 0;
			
			// aapt resource value: 1
			public const int TabLayout_tabContentStart = 1;
			
			// aapt resource value: 2
			public const int TabLayout_tabGravity = 2;
			
			// aapt resource value: 3
			public const int TabLayout_tabIndicatorColor = 3;
			
			// aapt resource value: 4
			public const int TabLayout_tabIndicatorHeight = 4;
			
			// aapt resource value: 5
			public const int TabLayout_tabMaxWidth = 5;
			
			// aapt resource value: 6
			public const int TabLayout_tabMinWidth = 6;
			
			// aapt resource value: 7
			public const int TabLayout_tabMode = 7;
			
			// aapt resource value: 8
			public const int TabLayout_tabPadding = 8;
			
			// aapt resource value: 9
			public const int TabLayout_tabPaddingBottom = 9;
			
			// aapt resource value: 10
			public const int TabLayout_tabPaddingEnd = 10;
			
			// aapt resource value: 11
			public const int TabLayout_tabPaddingStart = 11;
			
			// aapt resource value: 12
			public const int TabLayout_tabPaddingTop = 12;
			
			// aapt resource value: 13
			public const int TabLayout_tabSelectedTextColor = 13;
			
			// aapt resource value: 14
			public const int TabLayout_tabTextAppearance = 14;
			
			// aapt resource value: 15
			public const int TabLayout_tabTextColor = 15;
			
			// aapt resource value: { 0x1010150,0x101009A,0x7F030019,0x7F03001A,0x7F03001B,0x7F03001C,0x7F03001E,0x7F03001F,0x7F030034,0x7F030035,0x7F030036,0x7F030049,0x7F03004A,0x7F03004B,0x7F03004C,0x7F03004D }
			public static int[] TextInputLayout = new int[] {
					16843088,
					16842906,
					2130903065,
					2130903066,
					2130903067,
					2130903068,
					2130903070,
					2130903071,
					2130903092,
					2130903093,
					2130903094,
					2130903113,
					2130903114,
					2130903115,
					2130903116,
					2130903117};
			
			// aapt resource value: 0
			public const int TextInputLayout_android_hint = 0;
			
			// aapt resource value: 1
			public const int TextInputLayout_android_textColorHint = 1;
			
			// aapt resource value: 2
			public const int TextInputLayout_counterEnabled = 2;
			
			// aapt resource value: 3
			public const int TextInputLayout_counterMaxLength = 3;
			
			// aapt resource value: 4
			public const int TextInputLayout_counterOverflowTextAppearance = 4;
			
			// aapt resource value: 5
			public const int TextInputLayout_counterTextAppearance = 5;
			
			// aapt resource value: 6
			public const int TextInputLayout_errorEnabled = 6;
			
			// aapt resource value: 7
			public const int TextInputLayout_errorTextAppearance = 7;
			
			// aapt resource value: 8
			public const int TextInputLayout_hintAnimationEnabled = 8;
			
			// aapt resource value: 9
			public const int TextInputLayout_hintEnabled = 9;
			
			// aapt resource value: 10
			public const int TextInputLayout_hintTextAppearance = 10;
			
			// aapt resource value: 11
			public const int TextInputLayout_passwordToggleContentDescription = 11;
			
			// aapt resource value: 12
			public const int TextInputLayout_passwordToggleDrawable = 12;
			
			// aapt resource value: 13
			public const int TextInputLayout_passwordToggleEnabled = 13;
			
			// aapt resource value: 14
			public const int TextInputLayout_passwordToggleTint = 14;
			
			// aapt resource value: 15
			public const int TextInputLayout_passwordToggleTintMode = 15;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
